/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OwnableDiamond } from "./OwnableDiamond";
export type { OwnableDiamondStorage } from "./OwnableDiamondStorage";
