/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../../common";

export interface OwnableDiamondInterface extends utils.Interface {
  functions: {
    "DIAMOND_STORAGE_SLOT()": FunctionFragment;
    "OWNABLE_DIAMOND_STORAGE_SLOT()": FunctionFragment;
    "addFacet(address,bytes4[])": FunctionFragment;
    "getFacetBySelector(bytes4)": FunctionFragment;
    "getFacetSelectors(address)": FunctionFragment;
    "getFacets()": FunctionFragment;
    "owner()": FunctionFragment;
    "removeFacet(address,bytes4[])": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateFacet(address,bytes4[],bytes4[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "DIAMOND_STORAGE_SLOT"
      | "DIAMOND_STORAGE_SLOT()"
      | "OWNABLE_DIAMOND_STORAGE_SLOT"
      | "OWNABLE_DIAMOND_STORAGE_SLOT()"
      | "addFacet"
      | "addFacet(address,bytes4[])"
      | "getFacetBySelector"
      | "getFacetBySelector(bytes4)"
      | "getFacetSelectors"
      | "getFacetSelectors(address)"
      | "getFacets"
      | "getFacets()"
      | "owner"
      | "owner()"
      | "removeFacet"
      | "removeFacet(address,bytes4[])"
      | "transferOwnership"
      | "transferOwnership(address)"
      | "updateFacet"
      | "updateFacet(address,bytes4[],bytes4[])"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "DIAMOND_STORAGE_SLOT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DIAMOND_STORAGE_SLOT()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OWNABLE_DIAMOND_STORAGE_SLOT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OWNABLE_DIAMOND_STORAGE_SLOT()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addFacet",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "addFacet(address,bytes4[])",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getFacetBySelector",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getFacetBySelector(bytes4)",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getFacetSelectors",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getFacetSelectors(address)",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "getFacets", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getFacets()",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner()", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeFacet",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "removeFacet(address,bytes4[])",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership(address)",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFacet",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BytesLike>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFacet(address,bytes4[],bytes4[])",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BytesLike>[]
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "DIAMOND_STORAGE_SLOT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DIAMOND_STORAGE_SLOT()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OWNABLE_DIAMOND_STORAGE_SLOT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OWNABLE_DIAMOND_STORAGE_SLOT()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addFacet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addFacet(address,bytes4[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFacetBySelector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFacetBySelector(bytes4)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFacetSelectors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFacetSelectors(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getFacets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFacets()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner()", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeFacet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeFacet(address,bytes4[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFacet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFacet(address,bytes4[],bytes4[])",
    data: BytesLike
  ): Result;

  events: {};
}

export interface OwnableDiamond extends BaseContract {
  contractName: "OwnableDiamond";

  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: OwnableDiamondInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DIAMOND_STORAGE_SLOT(overrides?: CallOverrides): Promise<[string]>;

    "DIAMOND_STORAGE_SLOT()"(overrides?: CallOverrides): Promise<[string]>;

    OWNABLE_DIAMOND_STORAGE_SLOT(overrides?: CallOverrides): Promise<[string]>;

    "OWNABLE_DIAMOND_STORAGE_SLOT()"(
      overrides?: CallOverrides
    ): Promise<[string]>;

    addFacet(
      facet_: PromiseOrValue<string>,
      selectors_: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "addFacet(address,bytes4[])"(
      facet_: PromiseOrValue<string>,
      selectors_: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getFacetBySelector(
      selector_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string] & { facet_: string }>;

    "getFacetBySelector(bytes4)"(
      selector_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string] & { facet_: string }>;

    getFacetSelectors(
      facet_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string[]] & { selectors_: string[] }>;

    "getFacetSelectors(address)"(
      facet_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string[]] & { selectors_: string[] }>;

    getFacets(
      overrides?: CallOverrides
    ): Promise<[string[]] & { facets_: string[] }>;

    "getFacets()"(
      overrides?: CallOverrides
    ): Promise<[string[]] & { facets_: string[] }>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    removeFacet(
      facet_: PromiseOrValue<string>,
      selectors_: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "removeFacet(address,bytes4[])"(
      facet_: PromiseOrValue<string>,
      selectors_: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateFacet(
      facet_: PromiseOrValue<string>,
      fromSelectors_: PromiseOrValue<BytesLike>[],
      toSelectors_: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "updateFacet(address,bytes4[],bytes4[])"(
      facet_: PromiseOrValue<string>,
      fromSelectors_: PromiseOrValue<BytesLike>[],
      toSelectors_: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  DIAMOND_STORAGE_SLOT(overrides?: CallOverrides): Promise<string>;

  "DIAMOND_STORAGE_SLOT()"(overrides?: CallOverrides): Promise<string>;

  OWNABLE_DIAMOND_STORAGE_SLOT(overrides?: CallOverrides): Promise<string>;

  "OWNABLE_DIAMOND_STORAGE_SLOT()"(overrides?: CallOverrides): Promise<string>;

  addFacet(
    facet_: PromiseOrValue<string>,
    selectors_: PromiseOrValue<BytesLike>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "addFacet(address,bytes4[])"(
    facet_: PromiseOrValue<string>,
    selectors_: PromiseOrValue<BytesLike>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getFacetBySelector(
    selector_: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  "getFacetBySelector(bytes4)"(
    selector_: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  getFacetSelectors(
    facet_: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  "getFacetSelectors(address)"(
    facet_: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getFacets(overrides?: CallOverrides): Promise<string[]>;

  "getFacets()"(overrides?: CallOverrides): Promise<string[]>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  removeFacet(
    facet_: PromiseOrValue<string>,
    selectors_: PromiseOrValue<BytesLike>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "removeFacet(address,bytes4[])"(
    facet_: PromiseOrValue<string>,
    selectors_: PromiseOrValue<BytesLike>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateFacet(
    facet_: PromiseOrValue<string>,
    fromSelectors_: PromiseOrValue<BytesLike>[],
    toSelectors_: PromiseOrValue<BytesLike>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "updateFacet(address,bytes4[],bytes4[])"(
    facet_: PromiseOrValue<string>,
    fromSelectors_: PromiseOrValue<BytesLike>[],
    toSelectors_: PromiseOrValue<BytesLike>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    DIAMOND_STORAGE_SLOT(overrides?: CallOverrides): Promise<string>;

    "DIAMOND_STORAGE_SLOT()"(overrides?: CallOverrides): Promise<string>;

    OWNABLE_DIAMOND_STORAGE_SLOT(overrides?: CallOverrides): Promise<string>;

    "OWNABLE_DIAMOND_STORAGE_SLOT()"(
      overrides?: CallOverrides
    ): Promise<string>;

    addFacet(
      facet_: PromiseOrValue<string>,
      selectors_: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<void>;

    "addFacet(address,bytes4[])"(
      facet_: PromiseOrValue<string>,
      selectors_: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<void>;

    getFacetBySelector(
      selector_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    "getFacetBySelector(bytes4)"(
      selector_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    getFacetSelectors(
      facet_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    "getFacetSelectors(address)"(
      facet_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getFacets(overrides?: CallOverrides): Promise<string[]>;

    "getFacets()"(overrides?: CallOverrides): Promise<string[]>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    removeFacet(
      facet_: PromiseOrValue<string>,
      selectors_: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<void>;

    "removeFacet(address,bytes4[])"(
      facet_: PromiseOrValue<string>,
      selectors_: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateFacet(
      facet_: PromiseOrValue<string>,
      fromSelectors_: PromiseOrValue<BytesLike>[],
      toSelectors_: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<void>;

    "updateFacet(address,bytes4[],bytes4[])"(
      facet_: PromiseOrValue<string>,
      fromSelectors_: PromiseOrValue<BytesLike>[],
      toSelectors_: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    DIAMOND_STORAGE_SLOT(overrides?: CallOverrides): Promise<BigNumber>;

    "DIAMOND_STORAGE_SLOT()"(overrides?: CallOverrides): Promise<BigNumber>;

    OWNABLE_DIAMOND_STORAGE_SLOT(overrides?: CallOverrides): Promise<BigNumber>;

    "OWNABLE_DIAMOND_STORAGE_SLOT()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addFacet(
      facet_: PromiseOrValue<string>,
      selectors_: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "addFacet(address,bytes4[])"(
      facet_: PromiseOrValue<string>,
      selectors_: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getFacetBySelector(
      selector_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getFacetBySelector(bytes4)"(
      selector_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFacetSelectors(
      facet_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getFacetSelectors(address)"(
      facet_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFacets(overrides?: CallOverrides): Promise<BigNumber>;

    "getFacets()"(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    removeFacet(
      facet_: PromiseOrValue<string>,
      selectors_: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "removeFacet(address,bytes4[])"(
      facet_: PromiseOrValue<string>,
      selectors_: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateFacet(
      facet_: PromiseOrValue<string>,
      fromSelectors_: PromiseOrValue<BytesLike>[],
      toSelectors_: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "updateFacet(address,bytes4[],bytes4[])"(
      facet_: PromiseOrValue<string>,
      fromSelectors_: PromiseOrValue<BytesLike>[],
      toSelectors_: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DIAMOND_STORAGE_SLOT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "DIAMOND_STORAGE_SLOT()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    OWNABLE_DIAMOND_STORAGE_SLOT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "OWNABLE_DIAMOND_STORAGE_SLOT()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addFacet(
      facet_: PromiseOrValue<string>,
      selectors_: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "addFacet(address,bytes4[])"(
      facet_: PromiseOrValue<string>,
      selectors_: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getFacetBySelector(
      selector_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getFacetBySelector(bytes4)"(
      selector_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFacetSelectors(
      facet_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getFacetSelectors(address)"(
      facet_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFacets(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getFacets()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeFacet(
      facet_: PromiseOrValue<string>,
      selectors_: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "removeFacet(address,bytes4[])"(
      facet_: PromiseOrValue<string>,
      selectors_: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateFacet(
      facet_: PromiseOrValue<string>,
      fromSelectors_: PromiseOrValue<BytesLike>[],
      toSelectors_: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "updateFacet(address,bytes4[],bytes4[])"(
      facet_: PromiseOrValue<string>,
      fromSelectors_: PromiseOrValue<BytesLike>[],
      toSelectors_: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
