/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MasterRouter__factory } from "./MasterRouter__factory";
export { MasterRouterStorage__factory } from "./MasterRouterStorage__factory";
