/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface MulticallRouterInterface extends utils.Interface {
  functions: {
    "multicall(address[],uint256[],bytes[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "multicall"
      | "multicall(address[],uint256[],bytes[])"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "multicall",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BytesLike>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "multicall(address[],uint256[],bytes[])",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BytesLike>[]
    ]
  ): string;

  decodeFunctionResult(functionFragment: "multicall", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "multicall(address[],uint256[],bytes[])",
    data: BytesLike
  ): Result;

  events: {};
}

export interface MulticallRouter extends BaseContract {
  contractName: "MulticallRouter";

  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MulticallRouterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    multicall(
      targets_: PromiseOrValue<string>[],
      values_: PromiseOrValue<BigNumberish>[],
      data_: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "multicall(address[],uint256[],bytes[])"(
      targets_: PromiseOrValue<string>[],
      values_: PromiseOrValue<BigNumberish>[],
      data_: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  multicall(
    targets_: PromiseOrValue<string>[],
    values_: PromiseOrValue<BigNumberish>[],
    data_: PromiseOrValue<BytesLike>[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "multicall(address[],uint256[],bytes[])"(
    targets_: PromiseOrValue<string>[],
    values_: PromiseOrValue<BigNumberish>[],
    data_: PromiseOrValue<BytesLike>[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    multicall(
      targets_: PromiseOrValue<string>[],
      values_: PromiseOrValue<BigNumberish>[],
      data_: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<void>;

    "multicall(address[],uint256[],bytes[])"(
      targets_: PromiseOrValue<string>[],
      values_: PromiseOrValue<BigNumberish>[],
      data_: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    multicall(
      targets_: PromiseOrValue<string>[],
      values_: PromiseOrValue<BigNumberish>[],
      data_: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "multicall(address[],uint256[],bytes[])"(
      targets_: PromiseOrValue<string>[],
      values_: PromiseOrValue<BigNumberish>[],
      data_: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    multicall(
      targets_: PromiseOrValue<string>[],
      values_: PromiseOrValue<BigNumberish>[],
      data_: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "multicall(address[],uint256[],bytes[])"(
      targets_: PromiseOrValue<string>[],
      values_: PromiseOrValue<BigNumberish>[],
      data_: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
