/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as routers from "./routers";
export type { routers };
import type * as storages from "./storages";
export type { storages };
