/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface SwapDiamondStorageInterface extends utils.Interface {
  functions: {
    "SWAP_DIAMOND_STORAGE_SLOT()": FunctionFragment;
    "getSelectorType(bytes4)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "SWAP_DIAMOND_STORAGE_SLOT"
      | "SWAP_DIAMOND_STORAGE_SLOT()"
      | "getSelectorType"
      | "getSelectorType(bytes4)"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "SWAP_DIAMOND_STORAGE_SLOT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SWAP_DIAMOND_STORAGE_SLOT()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSelectorType",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getSelectorType(bytes4)",
    values: [PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(
    functionFragment: "SWAP_DIAMOND_STORAGE_SLOT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SWAP_DIAMOND_STORAGE_SLOT()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSelectorType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSelectorType(bytes4)",
    data: BytesLike
  ): Result;

  events: {};
}

export interface SwapDiamondStorage extends BaseContract {
  contractName: "SwapDiamondStorage";

  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SwapDiamondStorageInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    SWAP_DIAMOND_STORAGE_SLOT(overrides?: CallOverrides): Promise<[string]>;

    "SWAP_DIAMOND_STORAGE_SLOT()"(overrides?: CallOverrides): Promise<[string]>;

    getSelectorType(
      selector_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[number] & { selectorType_: number }>;

    "getSelectorType(bytes4)"(
      selector_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[number] & { selectorType_: number }>;
  };

  SWAP_DIAMOND_STORAGE_SLOT(overrides?: CallOverrides): Promise<string>;

  "SWAP_DIAMOND_STORAGE_SLOT()"(overrides?: CallOverrides): Promise<string>;

  getSelectorType(
    selector_: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<number>;

  "getSelectorType(bytes4)"(
    selector_: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<number>;

  callStatic: {
    SWAP_DIAMOND_STORAGE_SLOT(overrides?: CallOverrides): Promise<string>;

    "SWAP_DIAMOND_STORAGE_SLOT()"(overrides?: CallOverrides): Promise<string>;

    getSelectorType(
      selector_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<number>;

    "getSelectorType(bytes4)"(
      selector_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<number>;
  };

  filters: {};

  estimateGas: {
    SWAP_DIAMOND_STORAGE_SLOT(overrides?: CallOverrides): Promise<BigNumber>;

    "SWAP_DIAMOND_STORAGE_SLOT()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSelectorType(
      selector_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getSelectorType(bytes4)"(
      selector_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    SWAP_DIAMOND_STORAGE_SLOT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "SWAP_DIAMOND_STORAGE_SLOT()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSelectorType(
      selector_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getSelectorType(bytes4)"(
      selector_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
