/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../common";

export interface BridgeRouterStorageInterface extends utils.Interface {
  functions: {
    "BRIDGE_ROUTER_STORAGE_SLOT()": FunctionFragment;
    "getBridgeAddress()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "BRIDGE_ROUTER_STORAGE_SLOT"
      | "BRIDGE_ROUTER_STORAGE_SLOT()"
      | "getBridgeAddress"
      | "getBridgeAddress()"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "BRIDGE_ROUTER_STORAGE_SLOT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BRIDGE_ROUTER_STORAGE_SLOT()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBridgeAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBridgeAddress()",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BRIDGE_ROUTER_STORAGE_SLOT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BRIDGE_ROUTER_STORAGE_SLOT()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBridgeAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBridgeAddress()",
    data: BytesLike
  ): Result;

  events: {};
}

export interface BridgeRouterStorage extends BaseContract {
  contractName: "BridgeRouterStorage";

  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BridgeRouterStorageInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    BRIDGE_ROUTER_STORAGE_SLOT(overrides?: CallOverrides): Promise<[string]>;

    "BRIDGE_ROUTER_STORAGE_SLOT()"(
      overrides?: CallOverrides
    ): Promise<[string]>;

    getBridgeAddress(
      overrides?: CallOverrides
    ): Promise<[string] & { bridge_: string }>;

    "getBridgeAddress()"(
      overrides?: CallOverrides
    ): Promise<[string] & { bridge_: string }>;
  };

  BRIDGE_ROUTER_STORAGE_SLOT(overrides?: CallOverrides): Promise<string>;

  "BRIDGE_ROUTER_STORAGE_SLOT()"(overrides?: CallOverrides): Promise<string>;

  getBridgeAddress(overrides?: CallOverrides): Promise<string>;

  "getBridgeAddress()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    BRIDGE_ROUTER_STORAGE_SLOT(overrides?: CallOverrides): Promise<string>;

    "BRIDGE_ROUTER_STORAGE_SLOT()"(overrides?: CallOverrides): Promise<string>;

    getBridgeAddress(overrides?: CallOverrides): Promise<string>;

    "getBridgeAddress()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    BRIDGE_ROUTER_STORAGE_SLOT(overrides?: CallOverrides): Promise<BigNumber>;

    "BRIDGE_ROUTER_STORAGE_SLOT()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBridgeAddress(overrides?: CallOverrides): Promise<BigNumber>;

    "getBridgeAddress()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    BRIDGE_ROUTER_STORAGE_SLOT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "BRIDGE_ROUTER_STORAGE_SLOT()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBridgeAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getBridgeAddress()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
