/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../common";

export interface TraderJoeRouterStorageInterface extends utils.Interface {
  functions: {
    "TRADER_JOE_ROUTER_STORAGE_SLOT()": FunctionFragment;
    "getTraderJoeRouter()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "TRADER_JOE_ROUTER_STORAGE_SLOT"
      | "TRADER_JOE_ROUTER_STORAGE_SLOT()"
      | "getTraderJoeRouter"
      | "getTraderJoeRouter()"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "TRADER_JOE_ROUTER_STORAGE_SLOT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TRADER_JOE_ROUTER_STORAGE_SLOT()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTraderJoeRouter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTraderJoeRouter()",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "TRADER_JOE_ROUTER_STORAGE_SLOT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TRADER_JOE_ROUTER_STORAGE_SLOT()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTraderJoeRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTraderJoeRouter()",
    data: BytesLike
  ): Result;

  events: {};
}

export interface TraderJoeRouterStorage extends BaseContract {
  contractName: "TraderJoeRouterStorage";

  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TraderJoeRouterStorageInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    TRADER_JOE_ROUTER_STORAGE_SLOT(
      overrides?: CallOverrides
    ): Promise<[string]>;

    "TRADER_JOE_ROUTER_STORAGE_SLOT()"(
      overrides?: CallOverrides
    ): Promise<[string]>;

    getTraderJoeRouter(
      overrides?: CallOverrides
    ): Promise<[string] & { traderJoeRouter_: string }>;

    "getTraderJoeRouter()"(
      overrides?: CallOverrides
    ): Promise<[string] & { traderJoeRouter_: string }>;
  };

  TRADER_JOE_ROUTER_STORAGE_SLOT(overrides?: CallOverrides): Promise<string>;

  "TRADER_JOE_ROUTER_STORAGE_SLOT()"(
    overrides?: CallOverrides
  ): Promise<string>;

  getTraderJoeRouter(overrides?: CallOverrides): Promise<string>;

  "getTraderJoeRouter()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    TRADER_JOE_ROUTER_STORAGE_SLOT(overrides?: CallOverrides): Promise<string>;

    "TRADER_JOE_ROUTER_STORAGE_SLOT()"(
      overrides?: CallOverrides
    ): Promise<string>;

    getTraderJoeRouter(overrides?: CallOverrides): Promise<string>;

    "getTraderJoeRouter()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    TRADER_JOE_ROUTER_STORAGE_SLOT(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "TRADER_JOE_ROUTER_STORAGE_SLOT()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTraderJoeRouter(overrides?: CallOverrides): Promise<BigNumber>;

    "getTraderJoeRouter()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    TRADER_JOE_ROUTER_STORAGE_SLOT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "TRADER_JOE_ROUTER_STORAGE_SLOT()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTraderJoeRouter(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getTraderJoeRouter()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
