/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../common";

export interface UniswapV2RouterStorageInterface extends utils.Interface {
  functions: {
    "UNISWAP_V2_ROUTER_STORAGE_SLOT()": FunctionFragment;
    "getSwapV2Router()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "UNISWAP_V2_ROUTER_STORAGE_SLOT"
      | "UNISWAP_V2_ROUTER_STORAGE_SLOT()"
      | "getSwapV2Router"
      | "getSwapV2Router()"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "UNISWAP_V2_ROUTER_STORAGE_SLOT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UNISWAP_V2_ROUTER_STORAGE_SLOT()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSwapV2Router",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSwapV2Router()",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "UNISWAP_V2_ROUTER_STORAGE_SLOT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UNISWAP_V2_ROUTER_STORAGE_SLOT()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSwapV2Router",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSwapV2Router()",
    data: BytesLike
  ): Result;

  events: {};
}

export interface UniswapV2RouterStorage extends BaseContract {
  contractName: "UniswapV2RouterStorage";

  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: UniswapV2RouterStorageInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    UNISWAP_V2_ROUTER_STORAGE_SLOT(
      overrides?: CallOverrides
    ): Promise<[string]>;

    "UNISWAP_V2_ROUTER_STORAGE_SLOT()"(
      overrides?: CallOverrides
    ): Promise<[string]>;

    getSwapV2Router(
      overrides?: CallOverrides
    ): Promise<[string] & { swapV2Router_: string }>;

    "getSwapV2Router()"(
      overrides?: CallOverrides
    ): Promise<[string] & { swapV2Router_: string }>;
  };

  UNISWAP_V2_ROUTER_STORAGE_SLOT(overrides?: CallOverrides): Promise<string>;

  "UNISWAP_V2_ROUTER_STORAGE_SLOT()"(
    overrides?: CallOverrides
  ): Promise<string>;

  getSwapV2Router(overrides?: CallOverrides): Promise<string>;

  "getSwapV2Router()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    UNISWAP_V2_ROUTER_STORAGE_SLOT(overrides?: CallOverrides): Promise<string>;

    "UNISWAP_V2_ROUTER_STORAGE_SLOT()"(
      overrides?: CallOverrides
    ): Promise<string>;

    getSwapV2Router(overrides?: CallOverrides): Promise<string>;

    "getSwapV2Router()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    UNISWAP_V2_ROUTER_STORAGE_SLOT(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "UNISWAP_V2_ROUTER_STORAGE_SLOT()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSwapV2Router(overrides?: CallOverrides): Promise<BigNumber>;

    "getSwapV2Router()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    UNISWAP_V2_ROUTER_STORAGE_SLOT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "UNISWAP_V2_ROUTER_STORAGE_SLOT()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSwapV2Router(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getSwapV2Router()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
