/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../common";

export interface WrapRouterStorageInterface extends utils.Interface {
  functions: {
    "WRAP_ROUTER_STORAGE_SLOT()": FunctionFragment;
    "getWrappedNativeAddress()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "WRAP_ROUTER_STORAGE_SLOT"
      | "WRAP_ROUTER_STORAGE_SLOT()"
      | "getWrappedNativeAddress"
      | "getWrappedNativeAddress()"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "WRAP_ROUTER_STORAGE_SLOT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WRAP_ROUTER_STORAGE_SLOT()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWrappedNativeAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWrappedNativeAddress()",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "WRAP_ROUTER_STORAGE_SLOT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WRAP_ROUTER_STORAGE_SLOT()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWrappedNativeAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWrappedNativeAddress()",
    data: BytesLike
  ): Result;

  events: {};
}

export interface WrapRouterStorage extends BaseContract {
  contractName: "WrapRouterStorage";

  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: WrapRouterStorageInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    WRAP_ROUTER_STORAGE_SLOT(overrides?: CallOverrides): Promise<[string]>;

    "WRAP_ROUTER_STORAGE_SLOT()"(overrides?: CallOverrides): Promise<[string]>;

    getWrappedNativeAddress(
      overrides?: CallOverrides
    ): Promise<[string] & { wrappedNative_: string }>;

    "getWrappedNativeAddress()"(
      overrides?: CallOverrides
    ): Promise<[string] & { wrappedNative_: string }>;
  };

  WRAP_ROUTER_STORAGE_SLOT(overrides?: CallOverrides): Promise<string>;

  "WRAP_ROUTER_STORAGE_SLOT()"(overrides?: CallOverrides): Promise<string>;

  getWrappedNativeAddress(overrides?: CallOverrides): Promise<string>;

  "getWrappedNativeAddress()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    WRAP_ROUTER_STORAGE_SLOT(overrides?: CallOverrides): Promise<string>;

    "WRAP_ROUTER_STORAGE_SLOT()"(overrides?: CallOverrides): Promise<string>;

    getWrappedNativeAddress(overrides?: CallOverrides): Promise<string>;

    "getWrappedNativeAddress()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    WRAP_ROUTER_STORAGE_SLOT(overrides?: CallOverrides): Promise<BigNumber>;

    "WRAP_ROUTER_STORAGE_SLOT()"(overrides?: CallOverrides): Promise<BigNumber>;

    getWrappedNativeAddress(overrides?: CallOverrides): Promise<BigNumber>;

    "getWrappedNativeAddress()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    WRAP_ROUTER_STORAGE_SLOT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "WRAP_ROUTER_STORAGE_SLOT()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getWrappedNativeAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getWrappedNativeAddress()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
