/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as presets from "./presets";
export { Diamond__factory } from "./Diamond__factory";
export { DiamondStorage__factory } from "./DiamondStorage__factory";
