/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as presets from "./presets";
export type { presets };
export type { Diamond } from "./Diamond";
export type { DiamondStorage } from "./DiamondStorage";
