const SelectorType = {
  Undefined: 0,
  SwapDiamond: 1,
  MasterRouter: 2,
};

const Commands = {
  UNDEFINED: 0,
  BRIDGE_ERC20: 1,
  BRIDGE_ERC721: 2,
  BRIDGE_ERC1155: 3,
  BRIDGE_NATIVE: 4,
  TRANSFER_ERC20: 10,
  TRANSFER_ERC721: 11,
  TRANSFER_ERC1155: 12,
  TRANSFER_NATIVE: 13,
  WRAP_NATIVE: 20,
  UNWRAP_NATIVE: 21,
  MULTICALL: 25,
  UV2_SWAP_EXACT_TOKENS_FOR_TOKENS: 50,
  UV2_SWAP_TOKENS_FOR_EXACT_TOKENS: 51,
  UV2_SWAP_EXACT_ETH_FOR_TOKENS: 52,
  UV2_SWAP_TOKENS_FOR_EXACT_ETH: 53,
  UV2_SWAP_EXACT_TOKENS_FOR_ETH: 54,
  UV2_SWAP_ETH_FOR_EXACT_TOKENS: 55,
  EXACT_INPUT: 60,
  EXACT_OUTPUT: 61,
  TJ_SWAP_EXACT_TOKENS_FOR_TOKENS: 70,
  TJ_SWAP_TOKENS_FOR_EXACT_TOKENS: 71,
  TJ_SWAP_EXACT_AVAX_FOR_TOKENS: 72,
  TJ_SWAP_TOKENS_FOR_EXACT_AVAX: 73,
  TJ_SWAP_EXACT_TOKENS_FOR_AVAX: 74,
  TJ_SWAP_AVAX_FOR_EXACT_TOKENS: 75,
};

module.exports = {
  SelectorType,
  Commands,
};
