/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPeripheryPayments } from "./IPeripheryPayments";
export type { ISwapRouter } from "./ISwapRouter";
