/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  TraderJoeRouterStorage,
  TraderJoeRouterStorageInterface,
} from "../../../../contracts/integration-facets/storages/TraderJoeRouterStorage";

const _abi = [
  {
    inputs: [],
    name: "TRADER_JOE_ROUTER_STORAGE_SLOT",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTraderJoeRouter",
    outputs: [
      {
        internalType: "address",
        name: "traderJoeRouter_",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5060df8061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c80633a144e2d1460375780637d35e208146076575b600080fd5b7fc11be187cd5660797a6158ae4076db56a270a2c7b6f669e7c58a47d52a8b8f33546040516001600160a01b0390911681526020015b60405180910390f35b609c7fc11be187cd5660797a6158ae4076db56a270a2c7b6f669e7c58a47d52a8b8f3381565b604051908152602001606d56fea26469706673582212207a055e783c2f7c56cb39167fadf24c9b89e0d4eec524f941c927f0c010725a1864736f6c63430008090033";

type TraderJoeRouterStorageConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TraderJoeRouterStorageConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TraderJoeRouterStorage__factory extends ContractFactory {
  constructor(...args: TraderJoeRouterStorageConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "TraderJoeRouterStorage";
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<TraderJoeRouterStorage> {
    return super.deploy(overrides || {}) as Promise<TraderJoeRouterStorage>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): TraderJoeRouterStorage {
    return super.attach(address) as TraderJoeRouterStorage;
  }
  override connect(signer: Signer): TraderJoeRouterStorage__factory {
    return super.connect(signer) as TraderJoeRouterStorage__factory;
  }
  static readonly contractName: "TraderJoeRouterStorage";

  public readonly contractName: "TraderJoeRouterStorage";

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TraderJoeRouterStorageInterface {
    return new utils.Interface(_abi) as TraderJoeRouterStorageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TraderJoeRouterStorage {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as TraderJoeRouterStorage;
  }
}
