/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  UniswapV2RouterStorage,
  UniswapV2RouterStorageInterface,
} from "../../../../contracts/integration-facets/storages/UniswapV2RouterStorage";

const _abi = [
  {
    inputs: [],
    name: "UNISWAP_V2_ROUTER_STORAGE_SLOT",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getSwapV2Router",
    outputs: [
      {
        internalType: "address",
        name: "swapV2Router_",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b5060df8061001e6000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c80633e5aae47146037578063918e44d1146070575b600080fd5b605d7f424c8fc773ebbdd72550f0fbb40c2e1ea9ad00b943e8b8220cb6f8a25911185381565b6040519081526020015b60405180910390f35b7f424c8fc773ebbdd72550f0fbb40c2e1ea9ad00b943e8b8220cb6f8a259111853546040516001600160a01b039091168152602001606756fea26469706673582212206ba53a5a38494119e048bc84d4d415b4eade2e6357cf04d642b3072b159d7ea164736f6c63430008090033";

type UniswapV2RouterStorageConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: UniswapV2RouterStorageConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class UniswapV2RouterStorage__factory extends ContractFactory {
  constructor(...args: UniswapV2RouterStorageConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "UniswapV2RouterStorage";
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<UniswapV2RouterStorage> {
    return super.deploy(overrides || {}) as Promise<UniswapV2RouterStorage>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): UniswapV2RouterStorage {
    return super.attach(address) as UniswapV2RouterStorage;
  }
  override connect(signer: Signer): UniswapV2RouterStorage__factory {
    return super.connect(signer) as UniswapV2RouterStorage__factory;
  }
  static readonly contractName: "UniswapV2RouterStorage";

  public readonly contractName: "UniswapV2RouterStorage";

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): UniswapV2RouterStorageInterface {
    return new utils.Interface(_abi) as UniswapV2RouterStorageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UniswapV2RouterStorage {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as UniswapV2RouterStorage;
  }
}
