/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { OwnableDiamond__factory } from "./OwnableDiamond__factory";
export { OwnableDiamondStorage__factory } from "./OwnableDiamondStorage__factory";
